"""Local driver for the RunPod fit job.

Subcommands:
  create     create an H100 (fallback A100-80G) pod with our SSH key
  status     print pod status + SSH endpoint
  terminate  terminate the pod

Reads the API key from ~/.runpod/api_key or $RUNPOD_API_KEY. Pod id is
cached in out/runpod_pod.json. SSH keypair: out/runpod_ssh_key(.pub),
generated by the caller (see README).
"""

import json
import os
import pathlib
import sys
import time
import urllib.request

BASE = "https://rest.runpod.io/v1"
ROOT = pathlib.Path(__file__).resolve().parent.parent
POD_FILE = ROOT / "out" / "runpod_pod.json"
SSH_PUBKEY = ROOT / "out" / "runpod_ssh_key.pub"

GPU_PREFERENCE = ["NVIDIA H100 80GB HBM3", "NVIDIA A100 80GB PCIe", "NVIDIA A100-SXM4-80GB"]
IMAGE = "runpod/pytorch:2.8.0-py3.11-cuda12.8.1-cudnn-devel-ubuntu22.04"


def api_key() -> str:
    p = pathlib.Path.home() / ".runpod" / "api_key"
    if p.exists():
        return p.read_text().strip()
    key = os.environ.get("RUNPOD_API_KEY")
    if key:
        return key
    sys.exit("no API key: put it in ~/.runpod/api_key or $RUNPOD_API_KEY")


def call(method: str, path: str, body: dict | None = None) -> dict:
    req = urllib.request.Request(
        f"{BASE}{path}",
        method=method,
        headers={
            "Authorization": f"Bearer {api_key()}",
            "Content-Type": "application/json",
        },
        data=json.dumps(body).encode() if body is not None else None,
    )
    try:
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read() or "{}")
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")
        raise RuntimeError(f"{method} {path} -> {e.code}: {detail}") from None


def create() -> None:
    pubkey = SSH_PUBKEY.read_text().strip()
    last_err = None
    for cloud in ("SECURE", "COMMUNITY"):
        try:
            pod = call(
                "POST",
                "/pods",
                {
                    "name": "jlens-qwen7b-fit",
                    "imageName": IMAGE,
                    "gpuTypeIds": GPU_PREFERENCE,
                    "gpuCount": 1,
                    "cloudType": cloud,
                    "containerDiskInGb": 60,
                    "ports": ["22/tcp"],
                    "env": {"PUBLIC_KEY": pubkey},
                },
            )
            POD_FILE.parent.mkdir(exist_ok=True)
            POD_FILE.write_text(json.dumps(pod, indent=2))
            print(f"created pod {pod['id']} on {cloud}")
            return
        except RuntimeError as e:
            last_err = e
            print(f"{cloud} failed: {e}")
    sys.exit(f"could not create pod: {last_err}")


def pod_id() -> str:
    return json.loads(POD_FILE.read_text())["id"]


def status(wait: bool = False) -> None:
    deadline = time.time() + 600
    while True:
        pod = call("GET", f"/pods/{pod_id()}")
        desired = pod.get("desiredStatus")
        ip, ports = pod.get("publicIp"), pod.get("portMappings") or {}
        print(
            f"status={desired} gpu={pod.get('machine', {}).get('gpuTypeId')} "
            f"ip={ip} ports={ports} costPerHr={pod.get('costPerHr')}"
        )
        if ip and ports.get("22"):
            print(f"SSH: ssh -i out/runpod_ssh_key -p {ports['22']} root@{ip}")
            return
        if not wait or time.time() > deadline:
            return
        time.sleep(15)


def terminate() -> None:
    call("DELETE", f"/pods/{pod_id()}")
    print(f"terminated {pod_id()}")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "status"
    {"create": create, "status": lambda: status(wait="--wait" in sys.argv), "terminate": terminate}[cmd]()
